# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Re:Delivery - Email Based Order Tracking"
version: "0.0.1"
slug: redelivery
description: "Local, private package tracking from your email inbox"
url: "https://github.com/proconlon/redelivery"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
webui: "http://[HOST]:[PORT:8080]/dashboard"
init: false
map:
  - config:rw
options:
  email_user: "your_email@gmail.com"
  email_pass: "your_APP_password"
  web_port: 8080
schema:
  email_user: str
  email_pass: str
  web_port: int
host_network: true
image: "ghcr.io/proconlon/redelivery-{arch}"
ingress: true
ingress_port: 8080
ports:
  8080/tcp: 8080
panel_icon: "mdi:package-variant"